name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "选择要部署的分支"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - teek

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
      - run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
